apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-api-deployment
  name: my-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-api-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-api-deployment
    spec:
      containers:
        - image: ghcr.io/igallion/my-api:1.1
          name: my-api
          ports:
            - containerPort: 8000
          resources: {}
          imagePullPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-api-deployment
  name: my-api-service
spec:
  ports:
    - name: 8000-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: my-api-deployment
  type: ClusterIP
status:
  loadBalancer: {}
